// src/app/widgets/header/header.component.ts
import { Component } from '@angular/core';
import { AuthButtonComponent } from './auth-button/auth-button.component';
import { ThemeSwitchComponent } from '../../features/dark-mode/ui/theme-switch/theme-switch.component';

@Component({
    selector: 'app-header',
    imports: [AuthButtonComponent, ThemeSwitchComponent],
    templateUrl: './header.component.html',
})
export class HeaderComponent {}

<header class="py-4 border-b border-t shadow-sm rounded-b-xl">
    <div class="container mx-auto">
        <div class="flex flex-row justify-between items-center w-full">
            <app-theme-switch />

            <app-auth-button />
        </div>
    </div>
</header>

// src/widgets/header/ui/header/header.tsx
import { ThemeSwitch } from "@/features/dark-mode";
import { AuthButton } from "../auth-button";

export function Header() {
    return (
        <header className="py-4 border-b border-t shadow-sm rounded-b-xl">
            <div className="container mx-auto">
                <div className="flex flex-row justify-between items-center w-full">
                    <ThemeSwitch />

                    <AuthButton />
                </div>
            </div>
        </header>
    );
}
