// src/widgets/header/ui/auth-button/auth-button.tsx
import { ROUTES } from "@/shared/constants";
import { Button } from "@/shared/ui";
import { localStorageService } from "@/shared/utils";
import { useNavigate } from "react-router-dom";

export function AuthButton() {
    const hasToken = localStorageService.token.get() ? true : false;

    const navigate = useNavigate();

    const handleClick = () => {
        if (hasToken) {
            localStorageService.token.remove();
            navigate(ROUTES.INDEX);
        } else {
            navigate(ROUTES.AUTH.SIGN_IN);
        }
    };

    return (
        <Button className="block" onClick={handleClick}>
            {hasToken ? "Выйти" : "Войти"}
        </Button>
    );
}

// src/app/widgets/header/auth-button/auth-button.component.ts
import { Component } from '@angular/core';
import { localStorageService } from '../../../shared/utils';
import { Router } from '@angular/router';
import { ROUTES } from '../../../shared/constants';
import { ButtonComponent } from '../../../shared/ui/button/button.component';

@Component({
    selector: 'app-auth-button',
    imports: [ButtonComponent],
    templateUrl: './auth-button.component.html',
})
export class AuthButtonComponent {
    public hasToken = Boolean(localStorageService.token.get());

    public constructor(private router: Router) {}

    public onClick() {
        console.log('click');
        if (this.hasToken) {
            localStorageService.token.remove();
            this.router.navigate([ROUTES.INDEX]);
        } else {
            this.router.navigate([ROUTES.AUTH.SIGN_IN]);
        }
    }
}

<app-button variant="outline" (click)="onClick()">{{ `${hasToken ? "Выйти" : "Войти"}`}}</app-button>
